### ISSUE TITLE
List of Playlist Not Displaying Correctly

### ISSUE THREAD

**Issue by dibowz** [Daksh777/SpotifyNoPremium#80]
Hi, today my spotify got automatically updated, so I use update.bat after it finish updating. When the bat process is completed, my Spotify turns out to be weird with the scroll bar. Here's the evidence:

![Spotify](https://user-images.githubusercontent.com/32085882/175444869-88cb7ebe-5290-40c9-913d-43798ec01d33.gif)

**Comment by dibowz** [comment]
fixed by performing [this guide](https://github.com/Daksh777/SpotifyNoPremium/issues/46#issuecomment-1059945231)
thanks! :)

**Comment by Daksh777** [comment]
Hey, this is actually an issue with Spicetify. It's likely you'll get the issue again on relaunch.
For more info: https://github.com/spicetify/spicetify-cli/issues/1770

It's recommended to download the old version and block updates:

**Windows**

1. Download and install the old version from here: http://download.spotify.com/SpotifyFullSetup.exe
2. Run the following in *ADMIN* command prompt:
`
rm %localappdata%\Spotify\Update` (Change rm to del in Windows 7, or delete manually)
`mkdir %localappdata%\Spotify\Update
icacls %localappdata%\Spotify\Update /deny "%username%":D
icacls %localappdata%\Spotify\Update /deny "%username%":R`
3. Run `install.bat` or `update.bat` depending on your Spicetify installation

**Mac OS**

1. Download and install the old version from here: https://download.scdn.co/SpotifyInstaller.zip
2. Follow these steps to block the updates: https://youtu.be/lMDazdNJ1mo?t=93
3. Follow the steps in README to install the theme.

**Comment by dibowz** [comment]
> Hey, this is actually an issue with Spicetify. It's likely you'll get the issue again on relaunch. For more info: [spicetify/spicetify-cli#1770](https://github.com/spicetify/spicetify-cli/issues/1770)
> 
> It's recommended to download the old version and block updates while the issue gets fixed:

Hi, you're right. It happening again when I relaunch. But the main problem is from the album art cover being enlarged. When I reducing the album art and relaunch, the problem is gone. I'll get back to this issue if the problem persists.

**Comment by Daksh777** [comment]
Reducing the album art and restarting still does not help in my case, this is a very weird bug.

**Comment by Daksh777** [comment]
Hey @dibowz, I've updated the fix. You can upgrade to the new version and use Spotify normally.

**Comment by dibowz** [comment]
Hi, reducing the album art still make the scrollbar weird again upon restart. 

> Hey @dibowz, I've updated the fix, please see the edited message. You can upgrade to the new version and use Spotify normally.

Thank you for your update 😁

**Comment by Daksh777** [comment]
Hey @dibowz, someone has reported this issue as well. I'll close this issue since it's not related to the main topic of this issue. Please refer to #81
